Revert r84963: "Added {Get,Set}PersistentHostQuota"
failures in webkit tests:
QuotaManagerTest.GetUsage_WithModification:
.\quota\quota_manager_unittest.cc(645): error: Value of: 4000 + 50000 + 900000000
  Actual: 900054000
Expected: usage()
Which is: 900108000

BUG=None
TEST=None
TBR=tzik@google.com

Review URL: http://codereview.chromium.org/7004018

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@84968 0039d316-1c4b-4281-b951-d872f2087c98