Fix bug in history salt computation
Since the salt is stored on disk, also increase the db version number. This will cause a rebuild of the history database.

I added the following warning to clang to make sure we don't make this mistake anywhere else in the codebase:

/Volumes/MacintoshHD2/src/chrome-git/src/chrome/browser/visitedlink/visitedlink_master.cc:968:30: error: argument to 'sizeof' in 'memcpy' call is the same expression as the source; did you mean to provide an explicit length? [-Werror,-Wsizeof-pointer-memaccess]
  memcpy(salt_, salt, sizeof(salt));
                ~~~~         ^~~~
/Volumes/MacintoshHD2/src/chrome-git/src/chrome/browser/visitedlink/visitedlink_master.cc:964:17: note: declared here
    const uint8 salt[LINK_SALT_LENGTH])
                ^

/Volumes/MacintoshHD2/src/chrome-git/src/chrome/common/visitedlink_common.cc:84:31: error: sizeof on array function parameter will return size of 'const uint8 *' (aka 'const unsigned char *') instead of 'const uint8 [8]' [-Werror,-Wsizeof-array-argument]
  MD5Update(&ctx, salt, sizeof(salt));
                              ^
/Volumes/MacintoshHD2/src/chrome-git/src/chrome/common/visitedlink_common.cc:79:17: note: declared here
    const uint8 salt[LINK_SALT_LENGTH]) {
                ^

BUG=25629
TEST=none


Review URL: http://codereview.chromium.org/7068017

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@89443 0039d316-1c4b-4281-b951-d872f2087c98