Revert 155429 - Integrate the Windows 8 code into the Chromium tree.
Exception: Missing input files:
c:\b\build\slave\cr-win-rel\build\src\win8\metro_driver\..\win8\delegate_execute\chrome_util.h

http://build.chromium.org/p/chromium/builders/Win%20Builder/builds/37270/steps/runhooks/logs/stdio

BUG=127799
TEST=A Chromium build can run as the immersive browser on Windows 8.


Review URL: https://chromiumcodereview.appspot.com/10875008

TBR=robertshield@chromium.org
Review URL: https://chromiumcodereview.appspot.com/10919152

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@155435 0039d316-1c4b-4281-b951-d872f2087c98