Revert 157057 - views/examples: ShowExamplesWindow() should be exported.
views_examples_lib is a component target now, so in order to make it work in
shared_library builds, ShowExamplesWindow() function needs to be exported.

E:\b\build\slave\win\build\src\ui\views\examples\examples_window.cc(194) : error C2220: warning treated as error - no 'object' file generated
E:\b\build\slave\win\build\src\ui\views\examples\examples_window.cc(194) : warning C4273: 'views::examples::ShowExamplesWindow' : inconsistent dll linkage
        ..\..\ui/views/examples/examples_window.h(19) : see previous definition of 'ShowExamplesWindow'

We need to have another define for VIEWS_EXAMPLES_IMPLEMENTATION and views_examples_export.h

BUG=141187
TBR=ben@chromium.org

Review URL: https://codereview.chromium.org/10911328

TBR=tfarina@chromium.org
Review URL: https://codereview.chromium.org/10933115

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@157063 0039d316-1c4b-4281-b951-d872f2087c98