Revert "OTS roll (to r49)"
.\src\gdef.cc(353) : error C2220: warning treated as error - no 'object' file
generated
.\src\gdef.cc(353) : warning C4800: 'ots::OpenTypeGDEF *' : forcing value to
bool 'true' or 'false' (performance warning)
Build log was saved at
"file://c:\b\build\slave\cr-win-dbg\build\src\build\Debug\obj\ots\BuildLog.htm"
ots - 1 error(s), 1 warning(s)

This reverts commit fda237cebd3094d69b69c16f509ec0d98092d74b.

BUG=none
TEST=none
TBR=bashi@google.com

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@72949 0039d316-1c4b-4281-b951-d872f2087c98