Revert "Fix favorite and auto_connect property usage."
This reverts commit 7243b36c78901e597eacbba77c24165239c7ea88 / r66253:

Fix favorite and auto_connect property usage. BUG=chromium-os:8913 TEST=manually open chrome://settings/internet and see if remembered networks are listed properly. For DOMUI network menu, pass --enable-domui-menu for chrome to enable and check. Review URL: http://codereview.chromium.org/4818002

It broke the ChromeOS and arm compiles with:

chrome/browser/chromeos/options/wifi_config_view_browsertest.cc:44: error: ‘class chromeos::WifiNetwork’ has no member named ‘set_favorite’

TBR=kochi

git-svn-id: svn://svn.chromium.org/chrome/trunk/src@66258 0039d316-1c4b-4281-b951-d872f2087c98